[versions]
core-ktx = "1.9.0"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
fragment-ktx = "2.5.3"
ktlint = "11.3.1"
junit = "4.13.2"
android-ext-junit = "1.1.5"
agp = "8.0.1"
kotlin = "1.8.20"
detekt = "1.23.0"
gson = "2.10.1"
retrofit = "2.9.0"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

junit = { module = "junit:junit", version.ref = "junit" }
android-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-ext-junit" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
app = [
    "core-ktx", "appcompat", "material", "constraintlayout", "gson"
]
testing-local = [
    "junit"
]

testing-instrumented = [
    "android-ext-junit"
]

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = {id =  "io.gitlab.arturbosch.detekt", version.ref = "detekt"}