[versions]
core-ktx = "1.9.0"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
activity-ktx = "1.7.2"
ktlint = "11.3.1"
junit = "4.13.2"
android-ext-junit = "1.1.5"
agp = "8.0.1"
kotlin = "1.8.20"
detekt = "1.23.0"
gson = "2.10.1"
retrofit = "2.9.0"
shimmer = "0.5.0"
picasso = "2.8"
lottie = "6.0.0"
coroutines-android = "1.3.9"

edwnmrtnz-testing-local = "1.1"
edwnmrtnz-scopey = "1.1"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
edwnmrtnz-scopey = { module = "net.github.amaterasu:scopey", version.ref = "edwnmrtnz-scopey" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines-android" }

edwnmrtnz-testing-local = { module = "net.github.amaterasu:localtest", version.ref = "edwnmrtnz-testing-local" }
junit = { module = "junit:junit", version.ref = "junit" }
android-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-ext-junit" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
app = [
    "core-ktx", "appcompat", "material", "constraintlayout", "gson", "retrofit",
    "retrofit-converter-gson", "shimmer", "picasso", "activity-ktx", "lottie"
]
testing-local = [
    "junit", "edwnmrtnz-testing-local"
]

testing-instrumented = [
    "android-ext-junit"
]

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.0-Beta" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
android-lib = { id = "com.android.library", version.ref = "agp" }